---

#################################################
#                                               #
#    Request or renew the SSL certificate       #
#                                               #
#################################################


# Launch the CertBot Docker Compose app to get the SSL certificate
# - Nginx on port 80 with a acme-challenge directory
# - Certbot to request the SSL certificate


# Get information about the SSL certificate on the remote
- name: Stat of the SSL certificate
  stat:
    path: /home/ubuntu/.ssl/fullchain.pem
  register: ssl_certificate

# If the SSL certificate does not exist, request it
- name: Request SSL certificate
  include_tasks: request_ssl_certificate.yml
  when: ssl_certificate.stat.exists == false

# If the SSL certificate exists and is older than 60 days, renew it
- name: Renew SSL certificate
  include_tasks: renew_ssl_certificate.yml
  when: ssl_certificate.stat.exists == true
    and (ansible_date_time.epoch|float - ssl_certificate.stat.mtime ) > (60 * 24 * 3600)
