version: '3.8'


# ############################################################################ #
# #                                                                          # #
# #  DOCKER-COMPOSE FILE                                                     # #
# #                                                                          # #
# #  This file is used to build the docker containers and to run them.       # #
# #                                                                          # #
# #  The containers are:                                                     # #
# #                                                                          # #
# #  - MariaDB container                                                     # #
# #  - Wordpress container with php-fpm                                      # #
# #  - Nginx container with TLSv1.2 or TLSv1.3                               # #
# #  - PhpMyAdmin container                                                  # #
# #  - Redis container                                                       # #
# #                                                                          # #
# ############################################################################ #


services:


  # Nginx container
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - wordpress_volume:/var/www/html/:ro
      - aftc_volume:/var/www/aftc:ro
    networks:
      docker_network:
        aliases:
          - ${URL}
    depends_on:
      - wordpress
    restart: always


  # Wordpress container with php-fpm
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html:rw
    networks:
      - docker_network
    depends_on:
      - mariadb
      - redis
    restart: always


  # MariaDB container
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - MYSQL_DB_PREFIX=${MYSQL_DB_PREFIX}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - docker_network
    restart: always


  # PhpMyAdmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: ${SITE_URL}/phpmyadmin
    networks:
      - docker_network
    depends_on:
      - mariadb
    restart: always


  # Redis container
  redis:
    container_name: redis
    image: redis:7.2
    volumes:
      - redis_data:/data
    networks:
      - docker_network
    restart: always



volumes:


  # Wordpress files
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/wordpress
      o: bind


  # MariaDB database
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/mariadb
      o: bind


  # Nginx Config
  nginx_config:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/requirements/nginx
      o: bind


  # Nginx Certificates
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/.ssl
      o: bind


  # Redis
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/redis
      o: bind

  # Aftc
  aftc_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/requirements/aftc
      o: bind


networks:


  # Docker network
  docker_network:
    driver: bridge
