version: '3.8'


services:

  # MariaDB container
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql:rw
    environment:
      - MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DB_PREFIX=${MYSQL_DB_PREFIX}
    networks:
      - docker_network
    restart: always

  # Wordpress container with php-fpm
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/html:rw
    env_file: .env
    # environment:
    #   WORDPRESS_CONFIG_EXTRA: |
    #       /* Nginx Cache */
    #       define( 'RT_WP_NGINX_HELPER_CACHE_PATH', '/var/run/nginx-cache' );"
    depends_on:
      - mariadb
    networks:
      - docker_network
    restart: always

  # Nginx container with TLSv1.2 or TLSv1.3
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_config:/etc/nginx/conf.d:ro
      - wordpress_volume:/var/www/html/:ro
    depends_on:
      - wordpress
    networks:
      docker_network:
        aliases:
          - ${URL}
    restart: always


  # PhpMyAdmin container
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: ${SITE_URL}/phpmyadmin
    volumes:
      - nginx_certs:/cert:ro
    networks:
      - docker_network
    restart: always


  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - docker_network
    expose:
      - '6379'



networks:
  docker_network:
    driver: bridge



volumes:

  # Wordpress files
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/wordpress
      o: bind

  # MariaDB database
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/mariadb
      o: bind

  # Nginx Certificates
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/.ssl
      o: bind

  # Nginx Config
  nginx_config:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/requirements/nginx
      o: bind

  # Redis
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Inception/data/redis
      o: bind
